# Julia wrapper for header: /opt/local/include/gdal_frmts.h
# Automatically generated using Clang.jl wrap_c, version 0.0.0

@c None GDALRegister_GDB () libgdal
@c None GDALRegister_GTiff () libgdal
@c None GDALRegister_GXF () libgdal
@c None GDALRegister_OGDI () libgdal
@c None GDALRegister_HFA () libgdal
@c None GDALRegister_AAIGrid () libgdal
@c None GDALRegister_GRASSASCIIGrid () libgdal
@c None GDALRegister_AIGrid () libgdal
@c None GDALRegister_AIGrid2 () libgdal
@c None GDALRegister_CEOS () libgdal
@c None GDALRegister_SAR_CEOS () libgdal
@c None GDALRegister_SDTS () libgdal
@c None GDALRegister_ELAS () libgdal
@c None GDALRegister_EHdr () libgdal
@c None GDALRegister_GenBin () libgdal
@c None GDALRegister_PAux () libgdal
@c None GDALRegister_ENVI () libgdal
@c None GDALRegister_DOQ1 () libgdal
@c None GDALRegister_DOQ2 () libgdal
@c None GDALRegister_DTED () libgdal
@c None GDALRegister_MFF () libgdal
@c None GDALRegister_HKV () libgdal
@c None GDALRegister_PNG () libgdal
@c None GDALRegister_DDS () libgdal
@c None GDALRegister_GTA () libgdal
@c None GDALRegister_JPEG () libgdal
@c None GDALRegister_JPEG2000 () libgdal
@c None GDALRegister_JP2KAK () libgdal
@c None GDALRegister_JPIPKAK () libgdal
@c None GDALRegister_MEM () libgdal
@c None GDALRegister_JDEM () libgdal
@c None GDALRegister_RASDAMAN () libgdal
@c None GDALRegister_GRASS () libgdal
@c None GDALRegister_PNM () libgdal
@c None GDALRegister_GIF () libgdal
@c None GDALRegister_BIGGIF () libgdal
@c None GDALRegister_Envisat () libgdal
@c None GDALRegister_FITS () libgdal
@c None GDALRegister_ECW () libgdal
@c None GDALRegister_JP2ECW () libgdal
@c None GDALRegister_ECW_JP2ECW () libgdal
@c None GDALRegister_FujiBAS () libgdal
@c None GDALRegister_FIT () libgdal
@c None GDALRegister_VRT () libgdal
@c None GDALRegister_USGSDEM () libgdal
@c None GDALRegister_FAST () libgdal
@c None GDALRegister_HDF4 () libgdal
@c None GDALRegister_HDF4Image () libgdal
@c None GDALRegister_L1B () libgdal
@c None GDALRegister_LDF () libgdal
@c None GDALRegister_BSB () libgdal
@c None GDALRegister_XPM () libgdal
@c None GDALRegister_BMP () libgdal
@c None GDALRegister_GSC () libgdal
@c None GDALRegister_NITF () libgdal
@c None GDALRegister_RPFTOC () libgdal
@c None GDALRegister_ECRGTOC () libgdal
@c None GDALRegister_MrSID () libgdal
@c None GDALRegister_MG4Lidar () libgdal
@c None GDALRegister_PCIDSK () libgdal
@c None GDALRegister_BT () libgdal
@c None GDALRegister_DODS () libgdal
@c None GDALRegister_GMT () libgdal
@c None GDALRegister_netCDF () libgdal
@c None GDALRegister_LAN () libgdal
@c None GDALRegister_CPG () libgdal
@c None GDALRegister_AirSAR () libgdal
@c None GDALRegister_RS2 () libgdal
@c None GDALRegister_ILWIS () libgdal
@c None GDALRegister_PCRaster () libgdal
@c None GDALRegister_IDA () libgdal
@c None GDALRegister_NDF () libgdal
@c None GDALRegister_RMF () libgdal
@c None GDALRegister_BAG () libgdal
@c None GDALRegister_HDF5 () libgdal
@c None GDALRegister_HDF5Image () libgdal
@c None GDALRegister_MSGN () libgdal
@c None GDALRegister_MSG () libgdal
@c None GDALRegister_RIK () libgdal
@c None GDALRegister_Leveller () libgdal
@c None GDALRegister_SGI () libgdal
@c None GDALRegister_SRTMHGT () libgdal
@c None GDALRegister_DIPEx () libgdal
@c None GDALRegister_ISIS3 () libgdal
@c None GDALRegister_ISIS2 () libgdal
@c None GDALRegister_PDS () libgdal
@c None GDALRegister_IDRISI () libgdal
@c None GDALRegister_Terragen () libgdal
@c None GDALRegister_WCS () libgdal
@c None GDALRegister_WMS () libgdal
@c None GDALRegister_HTTP () libgdal
@c None GDALRegister_SDE () libgdal
@c None GDALRegister_GSAG () libgdal
@c None GDALRegister_GSBG () libgdal
@c None GDALRegister_GS7BG () libgdal
@c None GDALRegister_GRIB () libgdal
@c None GDALRegister_INGR () libgdal
@c None GDALRegister_ERS () libgdal
@c None GDALRegister_PALSARJaxa () libgdal
@c None GDALRegister_DIMAP () libgdal
@c None GDALRegister_GFF () libgdal
@c None GDALRegister_COSAR () libgdal
@c None GDALRegister_TSX () libgdal
@c None GDALRegister_ADRG () libgdal
@c None GDALRegister_SRP () libgdal
@c None GDALRegister_COASP () libgdal
@c None GDALRegister_BLX () libgdal
@c None GDALRegister_LCP () libgdal
@c None GDALRegister_PGCHIP () libgdal
@c None GDALRegister_TMS () libgdal
@c None GDALRegister_EIR () libgdal
@c None GDALRegister_GEOR () libgdal
@c None GDALRegister_TIL () libgdal
@c None GDALRegister_R () libgdal
@c None GDALRegister_Rasterlite () libgdal
@c None GDALRegister_EPSILON () libgdal
@c None GDALRegister_PostGISRaster () libgdal
@c None GDALRegister_NWT_GRD () libgdal
@c None GDALRegister_NWT_GRC () libgdal
@c None GDALRegister_SAGA () libgdal
@c None GDALRegister_KMLSUPEROVERLAY () libgdal
@c None GDALRegister_GTX () libgdal
@c None GDALRegister_LOSLAS () libgdal
@c None GDALRegister_Istar () libgdal
@c None GDALRegister_NTv2 () libgdal
@c None GDALRegister_CTable2 () libgdal
@c None GDALRegister_JP2OpenJPEG () libgdal
@c None GDALRegister_XYZ () libgdal
@c None GDALRegister_HF2 () libgdal
@c None GDALRegister_PDF () libgdal
@c None GDALRegister_JPEGLS () libgdal
@c None GDALRegister_MAP () libgdal
@c None GDALRegister_OZI () libgdal
@c None GDALRegister_ACE2 () libgdal
@c None GDALRegister_CTG () libgdal
@c None GDALRegister_E00GRID () libgdal
@c None GDALRegister_SNODAS () libgdal
@c None GDALRegister_WEBP () libgdal
@c None GDALRegister_ZMap () libgdal
@c None GDALRegister_NGSGEOID () libgdal
@c None GDALRegister_MBTiles () libgdal
@c None GDALRegister_ARG () libgdal
@c None GDALRegister_IRIS () libgdal

